
package boutiquedearomas.gui;

import boutiquedearomas.logica.Logica;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class VentanaBoutique extends javax.swing.JFrame {

    Logica control = new Logica();

    String cod, nom, prec, orig;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaBoutique.class.getName());

    /**
     * Creates new form VentanaBoutique
     */
    public VentanaBoutique() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/Icono.png")).getImage());
    }

    // Simplificar inputs
    private void inputDatos() {
        cod = inputCodigoProducto.getText();
        nom = inputNombreProducto.getText();
        prec = inputPrecioProducto.getText();
        orig = inputOrigenProducto.getText();
    }

    // Limpiar inputs
    private void limpiarInputs() {
        inputCodigoProducto.setText("");
        inputNombreProducto.setText("");
        inputOrigenProducto.setText("");
        inputPrecioProducto.setText("");
    }

    private boolean camposVacios() {
        if (inputCodigoProducto.getText().isEmpty() || inputNombreProducto.getText().isEmpty() || inputOrigenProducto.getText().isEmpty() || inputPrecioProducto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Los campos no pueden estar vacíos");
            return true;
        }
        return false;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cajaTitulo = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JLabel();
        txtOrigenProducto = new javax.swing.JLabel();
        inputCodigoProducto = new javax.swing.JTextField();
        inputNombreProducto = new javax.swing.JTextField();
        inputPrecioProducto = new javax.swing.JTextField();
        inputOrigenProducto = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        btnEditarProducto = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        btnBorrarUltimoRegistro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarResultados = new javax.swing.JTextArea();
        txtNombreEstudiante = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caja Boutique de Aromas");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(245, 236, 208));

        cajaTitulo.setBackground(new java.awt.Color(219, 213, 225));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo100px.png"))); // NOI18N

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(102, 36, 131));
        txtTitulo.setText("Caja Boutique de Aromas");

        javax.swing.GroupLayout cajaTituloLayout = new javax.swing.GroupLayout(cajaTitulo);
        cajaTitulo.setLayout(cajaTituloLayout);
        cajaTituloLayout.setHorizontalGroup(
                cajaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cajaTituloLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(imgLogo)
                                .addGap(53, 53, 53)
                                .addComponent(txtTitulo)
                                .addContainerGap(136, Short.MAX_VALUE))
        );
        cajaTituloLayout.setVerticalGroup(
                cajaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cajaTituloLayout.createSequentialGroup()
                                .addGroup(cajaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(cajaTituloLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(imgLogo))
                                        .addGroup(cajaTituloLayout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(txtTitulo)))
                                .addContainerGap(17, Short.MAX_VALUE))
        );

        txtCodigoProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCodigoProducto.setForeground(new java.awt.Color(102, 36, 131));
        txtCodigoProducto.setText("Código del producto");

        txtNombreProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNombreProducto.setForeground(new java.awt.Color(102, 36, 131));
        txtNombreProducto.setText("Nombre del producto");

        txtPrecioProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPrecioProducto.setForeground(new java.awt.Color(102, 36, 131));
        txtPrecioProducto.setText("Precio del producto");

        txtOrigenProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtOrigenProducto.setForeground(new java.awt.Color(102, 36, 131));
        txtOrigenProducto.setText("Origen del producto");

        inputCodigoProducto.setBackground(new java.awt.Color(249, 249, 249));

        inputNombreProducto.setBackground(new java.awt.Color(249, 249, 249));

        inputPrecioProducto.setBackground(new java.awt.Color(249, 249, 249));

        inputOrigenProducto.setBackground(new java.awt.Color(249, 249, 249));

        btnAgregarProducto.setBackground(new java.awt.Color(102, 36, 131));
        btnAgregarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(245, 236, 208));
        btnAgregarProducto.setText("Agregar Producto");
        btnAgregarProducto.addActionListener(this::btnAgregarProductoActionPerformed);

        btnEditarProducto.setBackground(new java.awt.Color(102, 36, 131));
        btnEditarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditarProducto.setForeground(new java.awt.Color(245, 236, 208));
        btnEditarProducto.setText("Editar Producto");
        btnEditarProducto.addActionListener(this::btnEditarProductoActionPerformed);

        btnEstadisticas.setBackground(new java.awt.Color(102, 36, 131));
        btnEstadisticas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEstadisticas.setForeground(new java.awt.Color(245, 236, 208));
        btnEstadisticas.setText("Calcular Estadísticas");
        btnEstadisticas.addActionListener(this::btnEstadisticasActionPerformed);

        btnBorrarUltimoRegistro.setBackground(new java.awt.Color(102, 36, 131));
        btnBorrarUltimoRegistro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBorrarUltimoRegistro.setForeground(new java.awt.Color(245, 236, 208));
        btnBorrarUltimoRegistro.setText("Borrar Último Registro");
        btnBorrarUltimoRegistro.addActionListener(this::btnBorrarUltimoRegistroActionPerformed);

        mostrarResultados.setEditable(false);
        mostrarResultados.setBackground(new java.awt.Color(249, 249, 249));
        mostrarResultados.setColumns(20);
        mostrarResultados.setRows(5);
        jScrollPane1.setViewportView(mostrarResultados);

        txtNombreEstudiante.setForeground(new java.awt.Color(179, 136, 21));
        txtNombreEstudiante.setText("Fabrizio Fernandini");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(25, Short.MAX_VALUE)
                                .addComponent(cajaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtCodigoProducto)
                                                        .addComponent(txtPrecioProducto))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(inputPrecioProducto)
                                                        .addComponent(inputCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(27, 27, 27)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtNombreProducto)
                                                        .addComponent(txtOrigenProducto))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(inputOrigenProducto)
                                                        .addComponent(inputNombreProducto)))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(btnAgregarProducto)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEditarProducto)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEstadisticas)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBorrarUltimoRegistro))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(281, 281, 281)
                                                .addComponent(txtNombreEstudiante)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(cajaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCodigoProducto)
                                        .addComponent(inputCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNombreProducto)
                                        .addComponent(inputNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtPrecioProducto)
                                        .addComponent(inputPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtOrigenProducto)
                                        .addComponent(inputOrigenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAgregarProducto)
                                        .addComponent(btnEditarProducto)
                                        .addComponent(btnBorrarUltimoRegistro)
                                        .addComponent(btnEstadisticas))
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreEstudiante)
                                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed

        inputDatos();

        if (camposVacios()) {
            return;
        }

        try {
            int precioProductoInt = Integer.parseInt(prec);

            if (precioProductoInt < 0) {
                JOptionPane.showMessageDialog(this, "El precio debe ser mayor o igual a 0 y debe ser un número entero.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número entero.");
            return;
        }

        control.agregarProducto(cod, nom, prec, orig);
        control.mostrarProductos(mostrarResultados);
        JOptionPane.showMessageDialog(this, "Producto agregado correctamente.");
        limpiarInputs();

    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProductoActionPerformed

        if (control.listaVacia()) {
            JOptionPane.showMessageDialog(this, "No hay productos registrados para editar. Ingrese un producto antes de editar.");
            mostrarResultados.setText("--- Lista de Productos ---\nNo existen productos registrados actualmente.");
            return;
        }

        inputDatos();

        if (camposVacios()) {
            return;
        }

        if (!control.existeProducto(cod)) {
            JOptionPane.showMessageDialog(this, "El código ingresado no existe.");
            return;
        }

        int confirmarEditar = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea editar el producto?", "Confirmar", JOptionPane.YES_NO_OPTION);

        if (confirmarEditar == JOptionPane.YES_OPTION) {

            boolean correcto = control.editarProducto(cod, nom, prec, orig);

            if (correcto) {
                control.mostrarProductos(mostrarResultados);
                JOptionPane.showMessageDialog(this, "Producto (s) modificado correctamente.");
                limpiarInputs();
            } else {
                JOptionPane.showMessageDialog(this, "El precio debe ser un número válido igual o mayor a 0.");
            }
        }

    }//GEN-LAST:event_btnEditarProductoActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        mostrarResultados.setText("");

        if (!control.listaVacia()) {
            control.mostrarProductos(mostrarResultados);
            control.mostrarEstadisticas(mostrarResultados);
            mostrarResultados.append("\n" + control.mensajeTotalGastado());
        } else {
            mostrarResultados.setText("--- Estadísticas ---\nNo existen productos registrados para mostrar estadísticas.");
        }

    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnBorrarUltimoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarUltimoRegistroActionPerformed
        if (!control.listaVacia()) {
            int confirmarEditar = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea eliminar el último producto?", "Confirmar", JOptionPane.YES_NO_OPTION);

            if (confirmarEditar == JOptionPane.YES_OPTION) {
                control.borrarUltimo();
                mostrarResultados.setText("");

                if (control.listaVacia()) {
                    mostrarResultados.setText("--- Lista de Productos ---\nNo existen productos registrados actualmente.");
                } else {
                    control.mostrarProductos(mostrarResultados);
                }

                JOptionPane.showMessageDialog(this, "Último producto eliminado correctamente.");
                limpiarInputs();
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existen productos registrados, no se borró ningún registro.");
            mostrarResultados.setText("--- Lista de Productos ---\nNo existen productos registrados actualmente.");
        }

    }//GEN-LAST:event_btnBorrarUltimoRegistroActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnBorrarUltimoRegistro;
    private javax.swing.JButton btnEditarProducto;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JPanel cajaTitulo;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JTextField inputCodigoProducto;
    private javax.swing.JTextField inputNombreProducto;
    private javax.swing.JTextField inputOrigenProducto;
    private javax.swing.JTextField inputPrecioProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mostrarResultados;
    private javax.swing.JLabel txtCodigoProducto;
    private javax.swing.JLabel txtNombreEstudiante;
    private javax.swing.JLabel txtNombreProducto;
    private javax.swing.JLabel txtOrigenProducto;
    private javax.swing.JLabel txtPrecioProducto;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
